function insertMovieInfo(){
	var movieName = [
					'Neighbors', 
					'Godzilla', 
					'X-Men: Dyas of Future Past', 
					'Million Dollar Arm', 
					'The Amazing Spider-Man 2', 
					'Godzilla 3D', 
					'Blended', 
					'X-Men: Days of Future Past in 3D', 
					'The Other Women', 
					'Heaven is for Real', 
					'Rio 2',
					'Captain America: The Winter Soldier',
					'Legends of Oz: Dorthys Return',
					'Moms Night Out',
					'The Amazing Spider-Man 2 in 3D',
					'Divergent',
					'The Grand Budapest Hotel',
					'Godzilla: An IMAX 3D Experience',
					'The Lego Movie',
					'Brick Mansions',
					'Mr.Peabody & Sherman',
					'Bears',
					'Draft Day',
					'Noah',
					'Muppests Most Wanted',
					'Transcendence',
					'Non-Stop',
					'Ride Along',
					'Need for Speed',
					'300: Rise of an Empire',
					'Frozen'
					]

	var Theater =   [
					{'Sharon Cinemas 8': ['4:35‎' , '‎7:15pm‎'], 'Showcase Cinema de Lux Patriot Place': [‎'2:30'‎ , '‎3:55‎' , ‎'4:55‎' , ‎'6:35‎' , ‎'7:45‎' , ‎'9:20‎', ‎'10:20pm‎'], 'Showcase Cinemas North Attleboro', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinemas Seekonk Route 6'},
					{'Sharon Cinemas 8', 'Showcase Cinema de Lux Patriot Place', 'Showcase Cinemas North Attleboro', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinemas Seekonk Route 6'},
					{'Sharon Cinemas 8', 'Showcase Cinema de Lux Patriot Place', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinema de Lux Randolph'},
					{'Sharon Cinemas 8', 'Showcase Cinema de Lux Patriot Place', 'Showcase Cinemas North Attleboro', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinemas Seekonk Route 6'},
					{'Sharon Cinemas 8', 'Showcase Cinema de Lux Patriot Place', 'Showcase Cinemas North Attleboro', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinemas Seekonk Route 6'},
					{'Showcase Cinema de Lux Patriot Place', 'Showcase Cinemas North Attleboro', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinemas Seekonk Route 6', 'Showcase Cinema de Lux Randolph'},
					{'Sharon Cinemas 8', 'Showcase Cinema de Lux Patriot Place', 'Showcase Cinemas North Attleboro', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinemas Seekonk Route 6'},
					{'Showcase Cinema de Lux Patriot Place', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinema de Lux Randolph'},
					{'Sharon Cinemas 8', 'Showcase Cinema de Lux Patriot Place', 'Showcase Cinemas North Attleboro', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinemas Seekonk Route 6'},
					{'Showcase Cinemas North Attleboro', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinemas Seekonk Route 6', 'Showcase Cinema de Lux Randolph'},
					{'Sharon Cinemas 8', 'Showcase Cinema de Lux Patriot Place', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinema de Lux Randolph'},
					{'Showcase Cinema de Lux Patriot Place', 'Showcase Cinemas North Attleboro', ' Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinemas Seekonk Route 6', 'Showcase Cinema de Lux Randolph'},
					{'Showcase Cinema de Lux Patriot Place', 'Showcase Cinemas North Attleboro', ' Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinemas Seekonk Route 6', 'Showcase Cinema de Lux Randolph'},
					{'Showcase Cinema de Lux Patriot Place', 'Showcase Cinema de Lux Randolph'},
					{'Showcase Cinema de Lux Patriot Place', 'Regal Silver City Galleria 10', 'Regal Swansea Stadium 12', 'Showcase Cinema de Lux Randolph'},
					{'Route One Cinema Pub'},
					{'Sharon Cinemas 8', 'Showcase Cinemas North Attleboro', 'Showcase Cinemas Seekonk Route 6'},
					{'Showcase Cinema de Lux Randolph'},
					{'East Providence 10'}
					{'Route One Cinema Pub', 'Showcase Cinema de Lux Randolph'},
					{'East Providence 10'},
					{'Showcase Cinemas North Attleboro'},
					{'Route One Cinema Pub', 'Showcase Cinema de Lux Patriot Place'},
					{'Showcase Cinemas North Attleboro'},
					{'Route One Cinema Pub', 'East Providence 10'},
					{'East Providence 10'},
					{'East Providence 10'},
					{'East Providence 10'},
					{'East Providence 10'},
					{'East Providence 10'},

					]
}
